config/routes.rb
SampleApp::Application.routes.draw do
  get "products/index"
  resources :users
  namespace :admin do 
    resources :users, except: [:new, :create]
    resources :posts
    resources :products
    resources :product_types
  end
  resources :posts
  resources :products
  resources :comments
  resources :microcomments
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'products#index'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home', to: 'static_pages#home'
  match '/signup', to: 'users#new'
  match '/index', to: 'users#show'
  match '/show', to: 'users#show' 
  match '/users', to: 'users#index'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"
  get "static_pages/contact"
  
  

  match '/', to: 'static_pages#home'

end

app/views/layouts/admin/_side_menu.html.erb
<div class="accordion" id="side_menu" >
<% side_menues.each do |menu|%>
  <div class="accordion-group">
    <div class="accordion-heading">
<% if menu[:collapses] %>
  <% if menu[:name_head] %>
    <%= link_to t(".#{menu[:group]}.header", name: menu[:name_head].call), "#", class: "accordion-toggle", "data-toggle" => "collapse", "data-target" => "#collapse-#{menu[:group]}" %>
  <% else %>
    <%= link_to t(".#{menu[:group]}.header"), "#", class: "accordion-toggle", "data-toggle" => "collapse", "data-target" => "#collapse-#{menu[:group]}" %>
  <% end %>
<% else %>
  <%= link_to t(".#{menu[:group]}.header"), menu[:heading].call, class: "accordion-toggle" %>
<% end %>
    </div>
<% if menu[:collapses] %>
    <div id="collapse-<%=menu[:group]%>" class="collapse<%= " in" if side_menu_include? menu[:collapses] %>">
<% menu[:collapses].each do |label, url_proc| %>
<%   if side_menu_include?({_: url_proc}) %>
<%     content_for :title do %>
        <%= t(".#{menu[:group]}.#{label}") %>       
<%     end %>
<%   end %>
      <div class="accordion-inner<%= " active" if side_menu_include?({_: url_proc}) %>">
        <%= link_to t(".#{menu[:group]}.#{label}"), url_proc.call %>
      </div>
<% end %>
    </div>
<% end %>
  </div>
<% end %>
</div>

app/views/layouts/admin/admin_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <title><%= content_for?(:title) ? yield(:title) : "SampleApp" %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <div class="container">
           <%= link_to "Home", home_path, id: "logo" %>
            <nav>
              <ul class="nav pull-right">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Help", help_path %></li>
                <% if signed_in? %>
                  <li><%= link_to "Users", users_path %></li>
                  <li><%= link_to "Posts", posts_path %></li>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Sign out", signout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Sign in", signin_path %></li>
                <% end %>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <%= render partial: "layouts/admin/side_menu" %>
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>