config/routes.rb
SampleApp::Application.routes.draw do
  get "products/index"
  resources :users
  namespace :admin do 
    resources :users, except: [:new, :create]
    resources :posts
    resources :products
    resources :product_types
  end
  resources :posts
  resources :products
  resources :comments
  resources :microcomments
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'products#index'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home', to: 'static_pages#home'
  match '/signup', to: 'users#new'
  match '/index', to: 'users#show'
  match '/show', to: 'users#show' 
  match '/users', to: 'users#index'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"
  get "static_pages/contact"
  
  

  match '/', to: 'static_pages#home'

end

app/models/admin/user.rb
class Admin::User < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  attr_accessible :email, :name, :password, :password_confirmation, :remember_token
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  mount_uploader :avatar, AvatarUploader

  def large_image
    "http://graph.facebook.com/#{self.uid}/picture?type=large"
  end

  def small_image
    "http://graph.facebook.com/#{self.uid}/picture?type=small"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  attr_accessible :email, :name, :password, :password_confirmation, :remember_token, :avatar, :tel, 
   :uid
  has_secure_password #de khai bao kei password va co the su dung authenticate
  # dam bao rang dia chi email co chu HOA va chu Thuong cung nhu nhau
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  mount_uploader :avatar, AvatarUploader
  
  validates :name,  presence: true, :length => { :maximum => 50,:minimum =>6 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  has_many :posts
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  # before_filter :admin_user

  def index
    @users = User.order(:updated_at).page(params[:page])
  end
  def new
    @user = Admin::User.new
  end

  def show
    @user = Admin::User.find(params[:id])
  end

  def create
    binding.pry
    @user = Admin::User.new(params.require(:admin_user).permit(:name, :admin))
    if @user.valid?
      @user.save
      redirect_to admin_user_path(@user), notice: :".created"
    else
      render :new
    end
  end

  def edit
    @user = Admin::User.find(params[:id])
  end

  def update
    @user = Admin::User.find(params[:id])
    user = params.require(:admin_user).permit(:name, :admin)
    if @user.update(user)
      redirect_to admin_user_path(@user), notice: :".updateted"
    else
      render :edit
    end
  end

  def destroy
    @user = Admin::User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :signed_in_user, only: [:index,:edit, :update]
  # before_filter :correct_user,   only: [:edit, :update]
  # before_filter :admin_user,     only: :destroy
  def new
  	@user = User.new
  end
  def show
  	@user = User.find(params[:id])
  	#@user = User.find(params[:id])
  end
  def index
    #@users = User.paginate(page: params[:page])
    @users=User.all
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      # Handle a successful save.
      sign_in @user
      flash[:result] = "Welcome to the Sample App!"
      redirect_to @user
    else
      #redirect_to root_path
      flash[:error] = "Invalid User!"
      render 'new'
    end
  end
  def edit
    @user=User.find(params[:id])
  end
  def update
    @user=User.find(params[:id])
    @user.attributes = params[:user]
    if @user.save
      flash[:succss]="Profiles updated"
      sign_in @user
      redirect_to @user
    else 
      flash[:error]="Invalid information"
      render 'edit'
    end
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path)  unless current_user?(@user)
    end
    def admin_user
      flash[:notice] = "You are not Admin"
      redirect_to(root_path)  unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar" )
  end
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :tel %>
      <%= f.text_field :tel %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= @user.avatar.present? ? image_tag(@user.avatar) : image_tag("http://www.sancoso.com/app/views/default/static/img/no-avatar.png") %>
      <%= f.file_field :avatar %><br />

      <%= f.submit "Save", class: "btn btn-large btn-primary" %><%= link_to "Cancel", user_path(@user), class: "btn btn-large"%>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<table class= "table table-bordered table-striped" width="40%" >
  <% @users.each do |user| %>
   <tr>
    <td rowspan = "5" width="130"><%= user.avatar.present? ? image_tag(user.avatar) : image_tag("http://www.sancoso.com/app/views/default/static/img/no-avatar.png") %></td>
  </tr>
  <tr>
    <td>Name: <%= link_to user.name, user_path(user) %></td>
  </tr>
  <tr>
    <td>Email: <%= user.email %></td>
  </tr>
  <tr>
    <td>Phone Number: <%= user.tel %></td>
  </tr>
  <tr>
    <td colspan="2">Posts: <%= user.posts.count %></td>
  </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <%= form_for @user, controller: "users", action: "create" do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
      	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      </h1>
    </section>
  </aside>
</div>
<h2>User Profile</h2>
<table class="table table-bordered table-striped" width="40%">
  <tr>
    <td rowspan = "5" width="130"><%= @user.avatar.present? ? image_tag(@user.avatar) : image_tag("http://www.sancoso.com/app/views/default/static/img/no-avatar.png") %></td>
  </tr>
  <tr>
    <td>Name: <%= @user.name %></td>
  </tr>
  <tr>
    <td>Email: <%= @user.email %></td>
  </tr>
  <tr>
    <td>Phone Number: <%= @user.tel %></td>
  </tr>
  <tr>
    <td colspan="2">Posts: <%= @user.posts.count %></td>
  </tr>
  <tr><td><%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" if correct_user?(@user) %></td></tr>
</table>
<h2>User posts</h2>
<table class = "table table-bordered table-striped">
  <% @user.posts.each  do |post| %>
    <tr>
      <td width="130"><%= post.user.avatar.present? ? image_tag(post.user.avatar) : image_tag("http://www.sancoso.com/app/views/default/static/img/no-avatar.png") %></td>
      <td><%=link_to post.title, post_path(post) %></td>
      <td><%= "Đã có lượt #{post.comments.count} comments" %></td>
    </tr>
  <% end %>
</table>