config/routes.rb
SampleApp::Application.routes.draw do
  get "products/index"
  resources :users
  namespace :admin do 
    resources :users, except: [:new, :create]
    resources :posts
    resources :products
    resources :product_types
  end
  resources :posts
  resources :products
  resources :comments
  resources :microcomments
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'products#index'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home', to: 'static_pages#home'
  match '/signup', to: 'users#new'
  match '/index', to: 'users#show'
  match '/show', to: 'users#show' 
  match '/users', to: 'users#index'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"
  get "static_pages/contact"
  
  

  match '/', to: 'static_pages#home'

end

app/models/admin/product.rb
class Admin::Product < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  attr_accessible :name, :size, :price, :product_type_id, :status, :amount, :fb_url, :product_image1, 
  :product_image2, :product_image3

  VALID_URL_REGEX = /\A(http:\/\/|https:\/\/)[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?\z/
  validates :name, presence: true

  mount_uploader :product_image1, ProductUploader
  mount_uploader :product_image2, ProductUploader
  mount_uploader :product_image3, ProductUploader

  belongs_to :product_type
  scope :order_by_created, ->{order "products.created_at DESC"}
  scope :order_by_updated, ->{order "products.created_at DESC"}

end

app/models/admin/product_type.rb
class Admin::ProductType < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true

  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  attr_accessible :name, :size, :price, :product_type_id, :status, :amount, :fb_url, :product_image1, 
  :product_image2, :product_image3

  validates :name, presence: true

  belongs_to :product_type

  mount_uploader :product_image1, ProductUploader
  mount_uploader :product_image2, ProductUploader
  mount_uploader :product_image3, ProductUploader

  scope :order_by_created, ->{order "products.created_at DESC"}
  scope :order_by_updated, ->{order "products.created_at DESC"}

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base

  validates :name, presence: true

  has_many :products
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_filter :admin_user
  
  def index
    @products = Admin::Product.order(:updated_at).page(params[:page])
  end
  def new
    @product = Admin::Product.new
  end

  def show
    @product = Admin::Product.find(params[:id])
  end

  def create
    @product = Admin::Product.new(params[:admin_product])
    if @product.valid?
      @product.save
      redirect_to admin_product_path(@product), notice: :".created"
    else
      render :new
    end
  end

  def edit
    @product = Admin::Product.find(params[:id])
  end

  def update
    @product = Admin::Product.find(params[:id])
    product = params[:admin_product]
    if @product.update_attributes(product)
      redirect_to admin_product_path(@product), notice: :".updateted"
    else
      render :edit
    end
  end

  def destroy
    @product = Admin::Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 layout "products_layouts"
  def index
    respond_to do |format|
      format.html do
        @q = Product.order_by_updated.search params[:q]
        @products = @q.result.page(params[:page])
      end
      format.csv {headers_for_downloading_csv}
    end
  end

  def show
    @q = Product.order_by_updated.search params[:q]
    @product = Admin::Product.find(params[:id])
  end
end

app/views/admin/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= render "errors", object: f.object %>
  <table class="table table-striped table-bordered">
    <tr>
      <td>Name: </td>
      <td><%= f.text_field :name%></td>
    </tr>
    <tr>
      <td>Size: </td>
      <td><%= f.text_field :size%></td>
    </tr>
    <tr>
    <tr>
      <td>Price: </td>
      <td><%= f.text_field :price%></td>
    </tr>
    <tr>
      <td>Amount: </td>
      <td><%= f.number_field :amount%></td>
    </tr>
    <tr>
      <td>Image 1: </td>
      <td>
        <%= f.file_field :product_image1 %>
        <%= image_tag @product.product_image1 if @product.product_image1? %>
      </td>
    </tr>
    <tr>
      <td>Image 2: </td>
      <td>
        <%= f.file_field :product_image2 %>
        <%= image_tag @product.product_image2 if @product.product_image2? %>
      </td>
    </tr>
    <tr>
      <td>Image 3: </td>
      <td>
        <%= f.file_field :product_image3 %>
        <%= image_tag @product.product_image3 if @product.product_image3? %>
      </td>
    </tr>
    <tr>
      <td>Status: </td>
      <td><%= f.select :status, options_for_select([["Còn hàng", 1],["Hết hàng", 0]]) %></td>
    </tr>
    <tr>
      <td>Type: </td>
      <td><%= f.collection_select :product_type_id, Admin::ProductType.all, :id, :name, {include_blank: "Chọn loại sản phẩm"} %></td>
    </tr>
    <tr>
      <td colspan="2" align="center"><%= f.submit "submit", class: "btn btn-primary" %></td>
    </tr>
  </table>
<% end %>

app/views/admin/products/edit.html.erb
<section id="products-edit">
  <h1 class="page-title"><%= t ".title" %></h1>
  <div class="actions">
    <%= link_to t(".back"), admin_products_path, class: :btn %>
  </div>
  <%= render "form" %>
</section>

app/views/admin/products/index.html.erb
<section id="products-index">
<% if notice %>
  <%= notice %>
<% end %>
<%= link_to "Add new product", new_admin_product_path %>
  <table class="table table-striped table-bordered table-products">
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Size</th>
      <th>Price</th>
      <th>Amount</th>
      <th>Type</th>
      <th>Image1</th>
      <th>Image2</th>
      <th>Image3</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Status</th>
      <th colspan="3">Action</th>
    </tr>
    <% @products.each_with_index do |product, i|%>
      <tr>
        <% j = params[:page] ? 5*((params[:page].to_i)-1) : 0 %>
        <td><%= i+j+1 %></td>
        <td><%= product.name %></td>
        <td><%= product.size %></td>
        <td><%= product.price %></td>
        <td><%= product.amount %></td>
        <td><%= product.product_type.try(:name) %></td>
        <td><%= image_tag(product.product_image1, width: "80", height: "120", alt: "anh 1") if product.product_image1? %></td>
        <td><%= image_tag(product.product_image2, width: "80", height: "120", alt: "anh 2") if product.product_image2? %></td>
        <td><%= image_tag(product.product_image3, width: "80", height: "120", alt: "anh 3") if product.product_image3? %></td>
        <td><%= product.created_at %></td>
        <td><%= product.updated_at %></td>
        <td><%= product.status==1 ? "Còn Hàng" : "Hết Hàng" %></td>
        <td><%= link_to "Show", admin_product_path(product), class: "btn" %></td>
        <td><%= link_to "Edit", edit_admin_product_path(product), class: "btn" %></td>
        <td><%= link_to "Destroy", admin_product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: "btn" %></td>
      </tr>
    <% end %>
  </table>
  <%= paginate @products %>
</section>

app/views/admin/products/new.html.erb
<section id="products-new">
  <h1 class="page-title"><%= t ".title" %></h1>
  <div class="actions">
    <%= link_to t(".back"), admin_products_path, class: :btn %>
  </div>
  <%= render "form" %>
</section>

app/views/admin/products/show.html.erb
<section products-show>
  <% if notice %>
    <%= notice %>
  <% end %>
  <table class="table table-striped table-bordered"> 
    <tr>
      <th>ID: </th>
      <td><%= @product.id%></td>
    </tr>
    <tr>
      <th>Name: </th>
      <td><%= @product.name%></td>
    </tr>
    <tr>
      <th>Size: </th>
      <td><%= @product.size%></td>
    </tr>
    <tr>
      <th>Amount: </th>
      <td><%= @product.amount %></td>
    </tr>
    <tr>
      <th>Type: </th>
      <td><%= @product.product_type.try(:name)%></td>
    </tr>
    <tr>
      <th>Status: </th>
      <td><%= @product.status==1 ? "Còn Hàng" : "Hết Hàng"%></td>
    </tr>
    <tr>
      <th>Image 1: </th>
      <td><%= image_tag @product.product_image1 if @product.product_image1? %></td>
    </tr>
    <tr>
      <th>Image 2: </th>
      <td><%= image_tag @product.product_image2 if @product.product_image2? %></td>
    </tr>
    <tr>
      <th>Image 3: </th>
      <td><%= image_tag @product.product_image3 if @product.product_image3? %></td>
    </tr>
    <tr>
      <td colspan="2">
        <%= link_to "Back", admin_products_path %>
        <%= link_to "Edit", edit_admin_product_path(@product) %>
        <%= link_to "Destroy", admin_product_path(@product), method: :delete, data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
</section>