config/routes.rb
SampleApp::Application.routes.draw do
  get "products/index"
  resources :users
  namespace :admin do 
    resources :users, except: [:new, :create]
    resources :posts
    resources :products
    resources :product_types
  end
  resources :posts
  resources :products
  resources :comments
  resources :microcomments
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'products#index'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home', to: 'static_pages#home'
  match '/signup', to: 'users#new'
  match '/index', to: 'users#show'
  match '/show', to: 'users#show' 
  match '/users', to: 'users#index'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"
  get "static_pages/contact"
  
  

  match '/', to: 'static_pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :user_id, :content, :title

  belongs_to :user
  has_many :comments

  scope :order_by_created, -> {order("created_at DESC")}
  validates :title, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :signed_in_user, only: [:new, :edit, :update]
  before_filter :admin_user,     only: :destroy
  before_filter :build_post, only: [:new, :create]
  before_filter :load_post, only: [:edit, :show, :update, :destroy]
  def new
  end
  def show
    limit = 3
    if params[:page].to_i >= 1 && params[:page].to_i <= ( @post.comments.count.to_f/3).ceil
      offset = params[:page] ? (params[:page].to_i - 1)*limit : 0
    end
    @comments = @post.comments.offset(offset).limit(limit).order_by_created
    respond_to do |format|
      format.js
      format.html
    end
  end
  def index
    limit = 3
    if params[:page].to_i >= 1 && params[:page].to_i <= (Post.count.to_f/3).ceil
      offset = params[:page] ? (params[:page].to_i - 1)*limit : 0
    end
    @posts=Post.offset(offset).limit(limit)
  end
  def create
    @post.attributes = params[:post]
    if @post.save
      # Handle a successful save.
      redirect_to posts_path()
    else
      #redirect_to root_path
      flash[:error] = "Invalid User!"
      render 'new'
    end
  end
  def edit
    @post=Post.find(params[:id])
  end
  def update
    @post=Post.find(params[:id])
    if @post.update_attributes(params[:post])
      flash[:succss]="Post updated"
      redirect_to @post
    else 
      flash[:error]="Error!"
      render 'edit'
    end
  end
  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post destroyed."
    redirect_to posts_url
  end
  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def admin_user
      flash[:notice] = "You are not Admin"
      redirect_to(root_path)  unless current_user.admin?
    end

    def build_post
      @post = current_user.posts.build
    end

    def load_post
      @post = Post.find(params[:id])
    end

    def correct_user
      @post = Post.find(params[:id])
      @user = @post.user
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/views/posts/_comments.html.erb
<% @comments.each_with_index do |comment, i|%>
<table class="table table-bordered table-striped">
	<tr>
		<td width="25"><%= comment.user.avatar.present? ? image_tag(comment.user.avatar) : image_tag("http://www.sancoso.com/app/views/default/static/img/no-avatar.png") %></td>
		<td>
			<div class ="comment-content">
				<%= comment.content.try(:html_safe) %>
				<%=link_to "x", comment_path(comment), method: :delete, data: {confirm: "delete"}, class: "delete"%>
				<table class = "table microcomment table-bordered table-striped">
          <tr>
          	<td colspan="2" id="tr-microcomment<%=comment.id%>">
        		<%= render "posts/microcomments", comment: comment %>
						</td>
					</tr>
					<tr>
						<td colspan=2>
							<div class="microcomment-form<%=comment.id%> microcomment-form">
								
							</div>
						</td>
					</tr>
      	</table>
      	<%=link_to "Comment", "#", class: "microcomment_link#{i}"%>
			</div>
		</td>
	</tr>
</table>
<% end %>

<script type="text/javascript">
	<% @comments.each_with_index do |comment, i| %>
  $(document).on("click", ".microcomment_link<%=i%>", function (e){
    e.preventDefault();
    var current_user = '<%= current_user %>';
    if(current_user == ''){
    	alert('Please signin');

    }
    else{
    	$(".microcomment-form<%=comment.id%>").html('<%= form_for comment.microcomments.build , remote: true, url: { controller: "microcomments", \
    	action: "create" }, id: "new_microcomment#{comment.id}" do |ff| %>\
							    <%= ff.text_field :content, class: "microcomment_content_field" %>\
							    <%= ff.hidden_field :comment_id, value: comment.id %>\
							    <%= ff.submit "Send", class: "btn microcomment-submit" %>\
							  	<% end %>');
    }
  })
  <% end %>
</script>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<%= render "application/errors", object: f.object %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :content %>
	<%= f.text_field :content , class: "comment_textarea" %>
	<%= f.submit "Send", class: "btn btn-large btn-primary" %>
<% end %>
<script type="text/javascript">
$("#comment_content").keypress(function(event) {
  if (event.which == 13) {
      event.preventDefault();
      $("#content-form").submit();
  }
});
tinymce.init({selector:'.comment_textarea'});
</script>

app/views/posts/_microcomments.html.erb
<% @micro_comments = @comment.nil? ? comment.microcomments : @comment.microcomments %>
<% @micro_comments.each_with_index do |mcomment, i|%>
	<table id="test1" calss="table table-bordered table-striped">
		<td width="20"><%= mcomment.comment.user.avatar.present? ? image_tag(mcomment.comment.user.avatar) : image_tag("http://www.sancoso.com/app/views/default/static/img/no-avatar.png") %></td>
		<td>
				<%= mcomment.content %>
		</td>
	</table>
<% end %>

app/views/posts/_paging.html.erb
<% total_page = (@post.comments.count.to_f/3).ceil%>
<% current_page = params[:page] ? params[:page].to_i : 1 %>
<% if total_page > 1%>
<%= link_to 'Fisrt', post_path(@post, page: 1), remote: true, class: "btn"%>
<% if current_page > 1 %>
	<%= link_to "<", post_path(@post, page: (current_page - 1)), remote: true,  id: "previous", class: "btn" %>
<% end %>
<%= link_to "#{current_page - 1}", post_path(@post, page: (current_page - 1)), id: "page#{current_page - 1}", remote: true, class: "btn" if current_page > 1%>
<%= link_to "#{current_page}", post_path(@post, page: current_page), remote: true, id: "page#{current_page}", class: "btn" %>
<%= link_to "#{current_page + 1}", post_path(@post, page: (current_page + 1)), remote: true, id: "page#{current_page + 1}", class: "btn" if current_page < total_page %>
<% if current_page < total_page %>
	<%= link_to ">", post_path(@post, page: (current_page + 1)), remote: true, id: "next", class: "btn" %>
<% end %>
<%= link_to 'Last', post_path(@post, page: total_page), remote: true, :"data-replace" => '#some_id',  class: "btn"%>
<%= "( Total page = #{total_page} )"%>
<% end %>

app/views/posts/edit.html.erb
<section id="posts-edit">
  <h1 class="page-title"><%= @post.title %></h1>
  <div class="actions">
    <%= link_to t(".back"), posts_path, class: :btn %>
  </div>
  <%= render "form" %>
</section>

app/views/posts/index.html.erb
<% provide(:title, "All Posts") %>
<div class = "content">
<table class = "table table-bordered table-striped">
  <% @posts.each  do |post| %>
  	<tr>
  		<td width="5%"><%= post.user.avatar.present? ? image_tag(post.user.avatar) : image_tag("http://www.sancoso.com/app/views/default/static/img/no-avatar.png") %></td>
  		<td><%= post.title %></td>
  	</tr>
    <tr>
      <td width="10%"></td>
      <td>
      	<div class="post-delete"><%=link_to "x", post_path(post), method: :delete, data: {confirm: "delete"}, class: "delete"%></div>
      	<%= short_content(post.content).try(:html_safe) %>
      	<div class="post-detail"><%=link_to "xem them..", post_path(post) %></div>
      </td>
    </tr>
  <% end %>
  <tr>
  	<td colspan = "2">
		<% total_page = (Post.count.to_f/3).ceil%>
		<% current_page = params[:page] ? params[:page].to_i : 1 %>
  	<% if total_page > 1 %>
  		<%= link_to "Fisrt","?page=1", id: "first", class: "btn" %>
  		<%= link_to "<","?page=#{current_page - 1}", id: "previous", class: "btn" %>
  		<% (1..total_page).each do |page|%>
  		<%= link_to "#{page}","?page=#{page}", id: "#{page}", class: "btn" %>
  		<% end %>
  		<%= link_to ">","?page=#{current_page + 1}", id: "next", class: "btn" %>
  		<%= link_to "Last", "?page=#{total_page}", id: "last", class: "btn" %></td>
  	<% end %>
  </tr>
</table>
</div>
<div class = "test"></div>
<h3><%= link_to "Create Post", new_post_path, class: "btn btn-large btn-primary"%></h3>

app/views/posts/new.html.erb
<% provide(:title, "Create new Post") %>
<section id="posts-new">
  <h1 class="page-title"><%= t ".create_new_post" %></h1>
  <div class="actions">
    <%= link_to t(".back"), posts_path, class: :btn %>
  </div>
  <%= render "form" %>
</section>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<div class = "post-show">
<table class = "table table-bordered" id="post-table">
  <tr>

    <td width = "45px">
      <%= @post.user.avatar.present? ? image_tag(@post.user.avatar) : image_tag("http://www.sancoso.com/app/views/default/static/img/no-avatar.png") %>
    </td>
    <td>
      <div class="post-delete"><%=link_to "Edit", edit_post_path(@post), class: "delete"%></div>
      <div class="post-title"><%= @post.title %></div>
    </td>
  </tr>
  <tr>
    <td></td>
    <td><%= @post.content.try(:html_safe) %></td>
  </tr>
  <tr>
    <th colspan = "2">Comment</th>
  </tr>
  <tr>
    <td></td>
    <td>
    	<div class = "table table-bordered table-striped comment">
        <div id="tr-comment">
      		<%= render "comments" %>
        </div>
    	</div>
    </td>
  </tr>
  <tr>
    <td></td>
  	<td>
      <div class="td-paging">
    		<%= render "paging"%>
      </div>
    </td>
  </tr>
<% if current_user %>
  <tr>
    <td></td>
    <td>
      <%= form_for @post.comments.build, remote: true, url: { controller: "comments", action: "create" }, html: {id: "content-form"} do |f| %>
        <%= f.text_field :content , class: "comment_textarea" %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%= f.submit "Send", class: "btn btn-large comment-submint" %>
      <% end %>
    </td>
  </tr>
<% else %>
  <tr>
    <td colspan="2">Please <%=link_to "Signin", signin_path %> to Add Comments</td>
  </tr>
<% end %>
</table>
</div>
<script type="text/javascript">
$("#comment_content").keypress(function(event) {
  if (event.which == 13) {
      event.preventDefault();
      $("#content-form").submit();
  }
});
tinymce.init({selector:'.comment_textarea'});
</script>

app/views/posts/show.js.erb
$(".comment").html("");
// $("#tr-comment").html("");
$(".comment").html("<%= escape_javascript(render('posts/comments')) %>")
$("#comment_content").val("");
$(".td-paging").html("<%= escape_javascript(render('posts/paging')) %>")